<?php
/**
 * Voice Secretary App Configuration
 * FusionPBX Application
 * 
 * ⚠️ MULTI-TENANT: TODAS as tabelas têm domain_uuid como foreign key obrigatória
 */

// Application details
$apps[$x]['name'] = "Voice Secretary";
$apps[$x]['uuid'] = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";
$apps[$x]['category'] = "AI";
$apps[$x]['subcategory'] = "";
$apps[$x]['version'] = "1.0.0";
$apps[$x]['license'] = "Proprietary";
$apps[$x]['url'] = "https://omniplay.com.br";
$apps[$x]['description']['en-us'] = "AI-powered virtual secretary for phone calls";
$apps[$x]['description']['pt-br'] = "Secretária virtual com IA para atendimento telefônico";

// Menu - Single entry (navigation handled within pages)
$apps[$x]['menu'][0]['title']['en-us'] = "Voice Secretary";
$apps[$x]['menu'][0]['title']['pt-br'] = "Secretária Virtual";
$apps[$x]['menu'][0]['uuid'] = "b2c3d4e5-f6a7-8901-bcde-f12345678901";
$apps[$x]['menu'][0]['parent_uuid'] = "fd29e39c-c936-f5fc-8e2b-611681b266b5"; // Apps menu
$apps[$x]['menu'][0]['category'] = "internal";
$apps[$x]['menu'][0]['path'] = "/app/voice_secretary/secretary.php";
$apps[$x]['menu'][0]['groups'][] = "superadmin";
$apps[$x]['menu'][0]['groups'][] = "admin";

// Permissions
$apps[$x]['permissions'][0]['name'] = "voice_secretary_view";
$apps[$x]['permissions'][0]['groups'][] = "superadmin";
$apps[$x]['permissions'][0]['groups'][] = "admin";

$apps[$x]['permissions'][1]['name'] = "voice_secretary_add";
$apps[$x]['permissions'][1]['groups'][] = "superadmin";
$apps[$x]['permissions'][1]['groups'][] = "admin";

$apps[$x]['permissions'][2]['name'] = "voice_secretary_edit";
$apps[$x]['permissions'][2]['groups'][] = "superadmin";
$apps[$x]['permissions'][2]['groups'][] = "admin";

$apps[$x]['permissions'][3]['name'] = "voice_secretary_delete";
$apps[$x]['permissions'][3]['groups'][] = "superadmin";
$apps[$x]['permissions'][3]['groups'][] = "admin";

$apps[$x]['permissions'][4]['name'] = "voice_secretary_providers";
$apps[$x]['permissions'][4]['groups'][] = "superadmin";
$apps[$x]['permissions'][4]['groups'][] = "admin";

$apps[$x]['permissions'][5]['name'] = "voice_secretary_documents";
$apps[$x]['permissions'][5]['groups'][] = "superadmin";
$apps[$x]['permissions'][5]['groups'][] = "admin";

// Database schema
// ⚠️ MULTI-TENANT: TODAS as tabelas têm domain_uuid NOT NULL

// Providers table
$apps[$x]['db'][0]['table']['name'] = "v_voice_ai_providers";
$apps[$x]['db'][0]['table']['parent'] = "";
$y = 0;
$apps[$x]['db'][0]['fields'][$y]['name'] = "voice_ai_provider_uuid";
$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][0]['fields'][$y]['key']['type'] = "primary";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "domain_uuid";
$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][0]['fields'][$y]['key']['type'] = "foreign";
$apps[$x]['db'][0]['fields'][$y]['key']['reference']['table'] = "v_domains";
$apps[$x]['db'][0]['fields'][$y]['key']['reference']['field'] = "domain_uuid";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "provider_type";
$apps[$x]['db'][0]['fields'][$y]['type'] = "text";
$apps[$x]['db'][0]['fields'][$y]['description']['en-us'] = "stt, tts, llm, embeddings";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "provider_name";
$apps[$x]['db'][0]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "config";
$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = "jsonb";
$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = "text";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "is_default";
$apps[$x]['db'][0]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][0]['fields'][$y]['default'] = "false";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "is_enabled";
$apps[$x]['db'][0]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][0]['fields'][$y]['default'] = "true";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "priority";
$apps[$x]['db'][0]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][0]['fields'][$y]['default'] = "0";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "insert_date";
$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = "timestamp";
$apps[$x]['db'][0]['fields'][$y]['default'] = "now()";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "insert_user";
$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "update_date";
$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = "timestamp";
$y++;
$apps[$x]['db'][0]['fields'][$y]['name'] = "update_user";
$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = "char(36)";

// Secretaries table
$apps[$x]['db'][1]['table']['name'] = "v_voice_secretaries";
$apps[$x]['db'][1]['table']['parent'] = "";
$y = 0;
$apps[$x]['db'][1]['fields'][$y]['name'] = "voice_secretary_uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][1]['fields'][$y]['key']['type'] = "primary";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "domain_uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][1]['fields'][$y]['key']['type'] = "foreign";
$apps[$x]['db'][1]['fields'][$y]['key']['reference']['table'] = "v_domains";
$apps[$x]['db'][1]['fields'][$y]['key']['reference']['field'] = "domain_uuid";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "secretary_name";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "company_name";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "extension";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "processing_mode";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$apps[$x]['db'][1]['fields'][$y]['default'] = "turn_based";
$apps[$x]['db'][1]['fields'][$y]['description']['en-us'] = "turn_based, realtime, auto";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "personality_prompt";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "greeting_message";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "farewell_message";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "farewell_keywords";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$apps[$x]['db'][1]['fields'][$y]['description']['en-us'] = "Comma-separated keywords that trigger call end (e.g., bye, goodbye, thanks bye)";
$apps[$x]['db'][1]['fields'][$y]['description']['pt-br'] = "Palavras separadas por vírgula que encerram a chamada (ex: tchau, falou, valeu)";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "outside_hours_message";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$apps[$x]['db'][1]['fields'][$y]['description']['en-us'] = "Message played when caller calls outside business hours";
$apps[$x]['db'][1]['fields'][$y]['description']['pt-br'] = "Mensagem reproduzida quando cliente liga fora do horário de atendimento";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "idle_timeout_seconds";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "30";
$apps[$x]['db'][1]['fields'][$y]['description']['en-us'] = "Seconds without activity before ending call";
$apps[$x]['db'][1]['fields'][$y]['description']['pt-br'] = "Segundos sem atividade antes de encerrar a chamada";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "max_duration_seconds";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "600";
$apps[$x]['db'][1]['fields'][$y]['description']['en-us'] = "Maximum call duration in seconds";
$apps[$x]['db'][1]['fields'][$y]['description']['pt-br'] = "Duração máxima da chamada em segundos";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "stt_provider_uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "tts_provider_uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "llm_provider_uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "embeddings_provider_uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "realtime_provider_uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "tts_voice_id";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "language";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$apps[$x]['db'][1]['fields'][$y]['default'] = "pt-BR";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "max_turns";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "20";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "transfer_extension";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "omniplay_webhook_url";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "omniplay_company_id";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$y++;

// Handoff Configuration
$apps[$x]['db'][1]['fields'][$y]['name'] = "handoff_enabled";
$apps[$x]['db'][1]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][1]['fields'][$y]['default'] = "true";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "handoff_timeout";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "30";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "handoff_keywords";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "handoff_queue_id";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "presence_check_enabled";
$apps[$x]['db'][1]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][1]['fields'][$y]['default'] = "true";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "time_condition_uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;

// Fallback Configuration
$apps[$x]['db'][1]['fields'][$y]['name'] = "fallback_ticket_enabled";
$apps[$x]['db'][1]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][1]['fields'][$y]['default'] = "true";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "fallback_action";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$apps[$x]['db'][1]['fields'][$y]['default'] = "ticket";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "fallback_user_id";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "fallback_priority";
$apps[$x]['db'][1]['fields'][$y]['type'] = "text";
$apps[$x]['db'][1]['fields'][$y]['default'] = "medium";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "fallback_notify_enabled";
$apps[$x]['db'][1]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][1]['fields'][$y]['default'] = "true";
$y++;

// Audio Configuration
$apps[$x]['db'][1]['fields'][$y]['name'] = "audio_warmup_chunks";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "15";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "audio_warmup_ms";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "400";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "audio_adaptive_warmup";
$apps[$x]['db'][1]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][1]['fields'][$y]['default'] = "true";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "jitter_buffer_min";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "100";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "jitter_buffer_max";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "300";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "jitter_buffer_step";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "40";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "stream_buffer_size";
$apps[$x]['db'][1]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][1]['fields'][$y]['default'] = "20";
$y++;

$apps[$x]['db'][1]['fields'][$y]['name'] = "enabled";
$apps[$x]['db'][1]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][1]['fields'][$y]['default'] = "true";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "insert_date";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "timestamp";
$apps[$x]['db'][1]['fields'][$y]['default'] = "now()";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "insert_user";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "update_date";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "timestamp";
$apps[$x]['db'][1]['fields'][$y]['default'] = "now()";
$y++;
$apps[$x]['db'][1]['fields'][$y]['name'] = "update_user";
$apps[$x]['db'][1]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][1]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][1]['fields'][$y]['type']['mysql'] = "char(36)";

// Documents table
$apps[$x]['db'][2]['table']['name'] = "v_voice_documents";
$apps[$x]['db'][2]['table']['parent'] = "";
$y = 0;
$apps[$x]['db'][2]['fields'][$y]['name'] = "voice_document_uuid";
$apps[$x]['db'][2]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][2]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][2]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][2]['fields'][$y]['key']['type'] = "primary";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "domain_uuid";
$apps[$x]['db'][2]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][2]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][2]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][2]['fields'][$y]['key']['type'] = "foreign";
$apps[$x]['db'][2]['fields'][$y]['key']['reference']['table'] = "v_domains";
$apps[$x]['db'][2]['fields'][$y]['key']['reference']['field'] = "domain_uuid";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "voice_secretary_uuid";
$apps[$x]['db'][2]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][2]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][2]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "document_name";
$apps[$x]['db'][2]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "document_type";
$apps[$x]['db'][2]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "content";
$apps[$x]['db'][2]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "file_path";
$apps[$x]['db'][2]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "file_size";
$apps[$x]['db'][2]['fields'][$y]['type'] = "numeric";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "chunk_count";
$apps[$x]['db'][2]['fields'][$y]['type'] = "numeric";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "processing_status";
$apps[$x]['db'][2]['fields'][$y]['type'] = "text";
$apps[$x]['db'][2]['fields'][$y]['default'] = "pending";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "enabled";
$apps[$x]['db'][2]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][2]['fields'][$y]['default'] = "true";
$y++;
$apps[$x]['db'][2]['fields'][$y]['name'] = "insert_date";
$apps[$x]['db'][2]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][2]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][2]['fields'][$y]['type']['mysql'] = "timestamp";
$apps[$x]['db'][2]['fields'][$y]['default'] = "now()";

// Conversations table
$apps[$x]['db'][3]['table']['name'] = "v_voice_conversations";
$apps[$x]['db'][3]['table']['parent'] = "";
$y = 0;
$apps[$x]['db'][3]['fields'][$y]['name'] = "voice_conversation_uuid";
$apps[$x]['db'][3]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][3]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][3]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][3]['fields'][$y]['key']['type'] = "primary";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "domain_uuid";
$apps[$x]['db'][3]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][3]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][3]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][3]['fields'][$y]['key']['type'] = "foreign";
$apps[$x]['db'][3]['fields'][$y]['key']['reference']['table'] = "v_domains";
$apps[$x]['db'][3]['fields'][$y]['key']['reference']['field'] = "domain_uuid";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "voice_secretary_uuid";
$apps[$x]['db'][3]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][3]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][3]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "call_uuid";
$apps[$x]['db'][3]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][3]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][3]['fields'][$y]['type']['mysql'] = "char(36)";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "caller_id_number";
$apps[$x]['db'][3]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "caller_id_name";
$apps[$x]['db'][3]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "start_time";
$apps[$x]['db'][3]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][3]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][3]['fields'][$y]['type']['mysql'] = "timestamp";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "end_time";
$apps[$x]['db'][3]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][3]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][3]['fields'][$y]['type']['mysql'] = "timestamp";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "total_turns";
$apps[$x]['db'][3]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][3]['fields'][$y]['default'] = "0";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "final_action";
$apps[$x]['db'][3]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "transfer_extension";
$apps[$x]['db'][3]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "ticket_created";
$apps[$x]['db'][3]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][3]['fields'][$y]['default'] = "false";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "ticket_id";
$apps[$x]['db'][3]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][3]['fields'][$y]['name'] = "insert_date";
$apps[$x]['db'][3]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][3]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][3]['fields'][$y]['type']['mysql'] = "timestamp";
$apps[$x]['db'][3]['fields'][$y]['default'] = "now()";

// Transfer Destinations table
// Destinos de transferência para handoff inteligente
$apps[$x]['db'][4]['table']['name'] = "v_voice_transfer_destinations";
$apps[$x]['db'][4]['table']['parent'] = "";
$y = 0;
$apps[$x]['db'][4]['fields'][$y]['name'] = "transfer_destination_uuid";
$apps[$x]['db'][4]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][4]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][4]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][4]['fields'][$y]['key']['type'] = "primary";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "domain_uuid";
$apps[$x]['db'][4]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][4]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][4]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][4]['fields'][$y]['key']['type'] = "foreign";
$apps[$x]['db'][4]['fields'][$y]['key']['reference']['table'] = "v_domains";
$apps[$x]['db'][4]['fields'][$y]['key']['reference']['field'] = "domain_uuid";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "secretary_uuid";
$apps[$x]['db'][4]['fields'][$y]['type']['pgsql'] = "uuid";
$apps[$x]['db'][4]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][4]['fields'][$y]['type']['mysql'] = "char(36)";
$apps[$x]['db'][4]['fields'][$y]['description']['en-us'] = "Optional: link to specific secretary";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "name";
$apps[$x]['db'][4]['fields'][$y]['type'] = "text";
$apps[$x]['db'][4]['fields'][$y]['description']['en-us'] = "Name for voice identification (e.g. Financeiro, João)";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "aliases";
$apps[$x]['db'][4]['fields'][$y]['type']['pgsql'] = "jsonb";
$apps[$x]['db'][4]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][4]['fields'][$y]['type']['mysql'] = "text";
$apps[$x]['db'][4]['fields'][$y]['description']['en-us'] = "JSON array of aliases for fuzzy matching";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "destination_type";
$apps[$x]['db'][4]['fields'][$y]['type'] = "text";
$apps[$x]['db'][4]['fields'][$y]['default'] = "extension";
$apps[$x]['db'][4]['fields'][$y]['description']['en-us'] = "extension, ring_group, queue, external, voicemail";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "destination_number";
$apps[$x]['db'][4]['fields'][$y]['type'] = "text";
$apps[$x]['db'][4]['fields'][$y]['description']['en-us'] = "Extension number, queue number, or external number";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "destination_context";
$apps[$x]['db'][4]['fields'][$y]['type'] = "text";
$apps[$x]['db'][4]['fields'][$y]['default'] = "default";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "ring_timeout_seconds";
$apps[$x]['db'][4]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][4]['fields'][$y]['default'] = "30";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "max_retries";
$apps[$x]['db'][4]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][4]['fields'][$y]['default'] = "1";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "retry_delay_seconds";
$apps[$x]['db'][4]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][4]['fields'][$y]['default'] = "5";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "fallback_action";
$apps[$x]['db'][4]['fields'][$y]['type'] = "text";
$apps[$x]['db'][4]['fields'][$y]['default'] = "offer_ticket";
$apps[$x]['db'][4]['fields'][$y]['description']['en-us'] = "offer_ticket, create_ticket, voicemail, return_agent, hangup";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "department";
$apps[$x]['db'][4]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "role";
$apps[$x]['db'][4]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "description";
$apps[$x]['db'][4]['fields'][$y]['type'] = "text";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "working_hours";
$apps[$x]['db'][4]['fields'][$y]['type']['pgsql'] = "jsonb";
$apps[$x]['db'][4]['fields'][$y]['type']['sqlite'] = "text";
$apps[$x]['db'][4]['fields'][$y]['type']['mysql'] = "text";
$apps[$x]['db'][4]['fields'][$y]['description']['en-us'] = "JSON with schedule: start, end, days, timezone";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "priority";
$apps[$x]['db'][4]['fields'][$y]['type'] = "numeric";
$apps[$x]['db'][4]['fields'][$y]['default'] = "100";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "is_enabled";
$apps[$x]['db'][4]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][4]['fields'][$y]['default'] = "true";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "is_default";
$apps[$x]['db'][4]['fields'][$y]['type'] = "boolean";
$apps[$x]['db'][4]['fields'][$y]['default'] = "false";
$apps[$x]['db'][4]['fields'][$y]['description']['en-us'] = "Default destination when no specific match";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "created_at";
$apps[$x]['db'][4]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][4]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][4]['fields'][$y]['type']['mysql'] = "timestamp";
$apps[$x]['db'][4]['fields'][$y]['default'] = "now()";
$y++;
$apps[$x]['db'][4]['fields'][$y]['name'] = "updated_at";
$apps[$x]['db'][4]['fields'][$y]['type']['pgsql'] = "timestamptz";
$apps[$x]['db'][4]['fields'][$y]['type']['sqlite'] = "date";
$apps[$x]['db'][4]['fields'][$y]['type']['mysql'] = "timestamp";

?>
